### ISSUE TITLE
 Inquiry About Releasing STaRwavLM Model Weights and Config

### ISSUE THREAD

**Issue by thunn** [sungnyun/ARMHuBERT#1]
Hi there 😄

Thank you for your work on ARMHuBERT and STaRwavLM.

I noticed in the [STaR paper](https://arxiv.org/abs/2312.09040) that STaRwavLM improves upon ARMwavLM-S, and I'm interested in exploring its applications. However, I couldn’t find the model weights or configuration files. Are there any plans to release them? Access to these would be helpful for further experimentation.

Looking forward to your response.

Thanks again!

**Comment by sausage-333** [comment]
Hi, I am the main author of STaR.
I just added the model weights and configuration files of STaRwavLM.
If there is something wrong, please note me.
Please enjoy!
